### ISSUE TITLE
Windows test failure

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-s3#8]
From https://github.com/elasticsearch/logstash/issues/2487
```
  27) LogStash::Inputs::S3#list_new_files should accepts a list of credentials for the aws-sdk, this is deprecated
     Failure/Error: expect{ config.register }.not_to raise_error
       expected no Exception, got #<Errno::ESRCH: No such process - C:\Users\jls\Documents\GitHub\logstash\tmp\mybackup> with backtrace:
         # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
         # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
         # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:57:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:112:in `run'
     # C:\Users\jls\Documents\GitHub\logstash\lib\logstash\runner.rb:170:in `run'
```

**Comment by ph** [comment]
Fixed the issues in https://github.com/logstash-plugins/logstash-input-s3/pull/9
